// src/routes/games/+page.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button/index.js';

	import * as Card from '$lib/components/ui/card/index.js';
</script>

<div class="flex items-center justify-center p-4">
	<Card.Root class="w-full max-w-prose">
		<Card.Header>
			<Card.Title>Expland</Card.Title>
		</Card.Header>
		<Card.Content>
			<p>
				Face adversity, hardship, enjoy adventure as well, and discover a second chance to fix past
				mistakes and become a better person in a mysterious world with nightmares and happiness just
				around the corner.
			</p>
		</Card.Content>
		<Card.Footer>
			<div>
				<Button href="https://github.com/NoeCoOfficial/Expland/releases" target="_blank" size="lg"
					>Download</Button
				>
				<Button variant="outline" href="/games/expland" size="lg">More</Button>
			</div>
		</Card.Footer>
	</Card.Root>
</div>

// app/games/page.tsx
import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import { Game } from "@/lib/interfaces";
import { GameComponent } from "./game";
import { ChevronDown, ChevronRight } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Games",
};

const games: Game[] = [
  {
    name: "Expland",
    description:
      "Face adversity, hardship, enjoy adventure as well, and discover a second chance to fix past mistakes and become a better person in a mysterious world with nightmares and happiness just around the corner.",
    image: { src: "/assets/expland/thumbnail.png", width: 1920, height: 1080 },
    url: "/games/expland",
    buttons: (
      <>
        <Button asChild>
          <Link
            href="https://github.com/NoeCoOfficial/Expland/releases"
            target="_blank"
          >
            Download
          </Link>
        </Button>
      </>
    ),
  },
];

export default function GamesPage() {
  return (
    <div className="flex flex-col gap-4 mx-auto p-2 w-full max-w-5xl md:mt-15 mt-10">
      {games.map((game, index) => (
        <GameComponent game={game} index={index} key={index} />
      ))}
    </div>
  );
}
